config/routes.rb
Rails.application.routes.draw do
  resources :messages
  root :to => "user_sessions#new"
  resources :user_sessions
  get 'home'           => 'home#index'
  post 'home'           => 'home#index'
  get 'login'          => 'user_sessions#new'
  get 'logout'         => 'user_sessions#destroy'
  # post 'authenticate'   => 'user_sessions#create'

  resources :users do
    # collection do
    #   post :following
    # end
    member do
      post :following
      post :unfollowing
    end
  end
  resources :posts do
    member do
      get :comment
      get :retwex
      get :user_favorite
    end
  end
  resources :albums
  #get 'assets/show'
  get 'attachments/:id/:style/:basename.:extension' => "assets#show"
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user

  # def send
  # end
   scope :received, -> (id) { where(recipient_id: id) }

  # def self.received(user)
  #   Message.where(recipient_id:user)
  # end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    #Al contestar un mensaje le pasamos el usuario de origen
    @users= params[:recipient_id] ? [User.find(params[:recipient_id])] : current_user.following
    @users=@users.map{|u|[u.login,u.id]}
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)
    @message.user_id=current_user.id
    #raise @message.inspect
    respond_to do |format|
      if @message.save
        format.html { redirect_to home_path, notice: 'Mensaje enviado correctamente.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to  home_path, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to  home_path, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:user, :recipient_id, :subject, :message)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.haml
.modal.fade
  -#.modal-dialog
  .modal-content.col-md-12
    .modal-header
      %h1 Mensaje
      .form-group
        - if @message.errors.any?
          #error_explanation
            %h2= "#{pluralize(@message.errors.count, "error")} prohibited this message from being saved:"
            %ul
              - @message.errors.full_messages.each do |message|
                %li= message
    = bootstrap_form_for @message, remote: true do |f|
      .modal-body.col-md-12
        .form-group
          -#.col-md-2
            = f.label :user
            = f.text_field :user
          .col-md-12
            %h4= f.label :recipient, "Destinatario"
            = f.select :recipient_id,  @users, include_blank:@users.count>1,hide_label:true, input_html:{class:"col-md-12 message-recipient-list"}
          .col-md-12
            %h4= f.label :subject, "Asunto"
            = f.text_field :subject,hide_label:true
          .col-md-12
            %h4= f.label :message, "Mensaje"
            = f.text_area :message,hide_label:true
      .modal-footer.col-md-12
        .actions
          -#.col-left
            = link_to 'Volver', home_path , class:"btn btn-info"
          .col-right
            = f.submit "Enviar", class:"btn btn-primary"

app/views/messages/edit.html.haml
= render 'form'

app/views/messages/index.html.haml
%h1 Listing messages

%table
  %thead
    %tr
      %th User
      %th Recipient
      %th Subject
      %th Message
      %th
      %th
      %th

  %tbody
    - @messages.each do |message|
      %tr
        %td= message.user_id
        %td= message.recipient_id
        %td= message.subject
        %td= message.message
        %td= link_to 'Show', message
        %td= link_to 'Edit', edit_message_path(message)
        %td= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Message', new_message_path

app/views/messages/new.html.haml
= render 'form'

app/views/messages/new.js.erb
$('<%= j render "form", title: "Nuevo mensaje" %>').modal();

app/views/messages/show.html.haml
%p#notice= notice

%p
  %b User:
  = @message.user_id
%p
  %b Recipient:
  = @message.recipient_id
%p
  %b Subject:
  = @message.subject
%p
  %b Message:
  = @message.message

= link_to 'Edit', edit_message_path(@message)
\|
= link_to 'Back', messages_path