config/routes.rb
Rails.application.routes.draw do
  resources :messages
  root :to => "user_sessions#new"
  resources :user_sessions
  get 'home'           => 'home#index'
  post 'home'           => 'home#index'
  get 'login'          => 'user_sessions#new'
  get 'logout'         => 'user_sessions#destroy'
  # post 'authenticate'   => 'user_sessions#create'

  resources :users do
    # collection do
    #   post :following
    # end
    member do
      post :following
      post :unfollowing
    end
  end
  resources :posts do
    member do
      get :comment
      get :retwex
      get :user_favorite
    end
  end
  resources :albums
  #get 'assets/show'
  get 'attachments/:id/:style/:basename.:extension' => "assets#show"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :require_user
  def index
    @posts = Post.where(ancestry:nil, user_id:current_user.id).or(Post.where(ancestry:nil, user_id:current_user.following))
    @search = Search.new
    if params[:search]
      @users=@search.find(params[:search][:user])
    else
      @users=User.where.not(id:current_user.id)
    end

    @notifications={}
    Post.roots.map(&:children).flatten
    @new_msgs       = Message.where(recipient_id:current_user, check_view:[false,nil])
    @new_followers  = UserConnection.where(followed_id:current_user, check_view:[false,nil])
    @new_posts      = Post.where(user_id:current_user.followers, check_view:[false,nil])
    @new_retwix     = Post.where(post_id:current_user, check_view:[false,nil])
    @new_comments   = Post.where(user_id:current_user, check_view:[false,nil]).map(&:children).flatten
    my_posts = Post.where(user_id:current_user)
    @new_favourites = UserFavoritePost.where(post_id:my_posts)
    # Genérico
    # Rails.application.eager_load!
    # cvs_models=ActiveRecord::Base.descendants.select{|des|!des.abstract_class}.select{|des|des.column_names.include?("check_view")}
    # #ActiveRecord::Base.descendants.select{|des|!des.abstract_class}.select{|des|des.column_names.include?("check_view")}.map(&:name)
    # #["Message", "Post", "PostConnection", "UserConnection"]
    # cvs_models.each do |model|
    #   if model.has_attribute?(:follower_id)
    #     #res=model.where(check_view: [false,nil], follower_id:current_user.id)
    #   elsif model.has_attribute?(:followed_id)
    #     res=model.where(check_view: [false,nil], followed_id:current_user.id)
    #   elsif model.has_attribute?(:user_id)
    #     res=model.where(check_view: [false,nil], user_id:current_user.id)
    #   end
    #   @notifications[model.name]||=res if res.present?
    # end
    #ActiveRecord::Base.descendants.select{|des|!des.abstract_class}.select{|des|des.column_names.include?("check_view")}.map(&:name)

    #session[:user_location] = Location.new(user_ip)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_favourites.html.haml
#usr-favourites-resume.col-md-12
  %h3
    Favoritos:

  %ul
  -UserFavoritePost.where(user_id:current_user).each do |fav|
    %li=fav.post.user.login
    %p.tab
      =fav.post.text

app/views/home/_follow.html.haml
%h3
  Siguiendo:
  =current_user.following.count
  %ul
  -current_user.following.each do |f|
    %li=f.login
%h3
  Seguidores:
  =UserConnection.where(followed_id:current_user).count
  %ul
  -UserConnection.where(followed_id:current_user).each do |f|
    %li=User.find_by_id(f.follower_id).login

app/views/home/_info_user.html.haml
-#.col-md-12
.usr-image-background.col-md-12
  .col-md-4
    =image_tag(current_user.asset.url, class:"img-circle user-info") if current_user.asset
  .col-md-8
    %center.usr-name-container
      .col-md-12.usr-name
        ="#{current_user.name} #{current_user.last_name}"
      .col-md-12.usr-login
        ="@#{current_user.login}"
.usr-follow-resume.col-md-12
  .col-md-4
    %p.usr-data
      TWIX
    %p.usr-counts
      =Post.my_posts(current_user.id).count
  .col-md-4
    %p.usr-data
      FOLLOWING
    %p.usr-counts
      =current_user.following.count
  .col-md-4
    %p.usr-data
      FOLLOWERS
    %p.usr-counts
      =UserConnection.where(followed_id:current_user).count
      -#=current_user.followers.count

app/views/home/_messages.html.haml
#messages.tab-pane.fade
  -#%h1
    Mensajes
  %h3
    Mensajes
    =link_to image_tag("message/send-message.png", class:"message-send"), new_message_path, remote: true
  %hr
    %ul.nav.nav-tabs
      %li.active
        %a{"data-toggle"=>"tab", href:"#received", "nav-email":"received"}Recibidos
        =#link_to "Recibidos", {"data-toggle"=>"tab", :anchor => "received"}
      %li
        %a{"data-toggle"=>"tab", href:"#send", "nav-email":"send"}Enviados
        =#link_to "Enviados",{"data-toggle"=>"tab", :anchor => "send"}
    .tab-content
      #received.tab-pane.fade.in.active
        %h3 Recibidos
        %table.table
          %thead
            %th
              Destinatario
            %th
              Fecha
            %th
              Asunto
            %th
              Mensaje
          %tbody
            -Message.received(current_user).each do |s|
              %tr
                %td.col-md-1
                  =User.find(s.recipient_id).login
                %td.col-md-2
                  =s.created_at.strftime("%H:%M %d-%m-%Y")
                %td.col-md-2
                  =s.subject
                %td.col-md-6
                  =s.message
                %td.col-md-1
                  =link_to "Contestar", new_message_path(recipient_id:s.user_id), remote: true
      #send.tab-pane.fade
        %h3 Enviados
        %table.table
          %thead
            %th
              Destinatario
            %th
              Fecha
            %th
              Asunto

          %tbody
            -current_user.messages.each do |s|
              %tr
                %td.col-md-1
                  =User.find(s.recipient_id).login
                %td.col-md-2
                  =s.created_at.strftime("%H:%M %d-%m-%Y")
                %td.col-md-2
                  =s.subject
                %td.col-md-6
                  =s.message

app/views/home/_notifications.html.haml
#notifications.tab-pane.fade
  %h3
    Notificaciones
  %hr
  -# %p
  -#   Recibirás notificaciones cuando alguien responde, marca como favorito o retwixtea tus TweX. También puedes recibir notificaciones cuando te envían mensajes directos o tienes nuevos seguidores.

  -if @new_msgs.any?
    %h4 Nuevos mensajes:
    %ul
    -@new_msgs.each do |m|
      %li="#{m.user.login} #{m.text}"

  -if @new_followers.any?
    %h4 Nuevos seguidores:
    %ul
    -@new_followers.each do |m|
      %li="#{m.follower.login}"

  -if @new_posts.any?
    %h4 Nuevas publicaciones:
    %ul
    -@new_posts.each do |m|
      %li=m.user.login

  -if @new_comments.any?
    %h4 Nuevos comentarios:
    %ul
    -@new_comments.each do |m|
      %li=m.follower.login

  -if @new_favourites.any?
    %h4 Favoritos:
    %ul
    -@new_favourites.each do |m|
      %li=m.user.login

app/views/home/_search.html.haml
#search.tab-pane.fade
  %h3
    Usuarios
  %hr
    = bootstrap_form_for @search,:url => home_path do |f|
      .col-md-11
        =f.search_field :user, hide_label:true
      .col-md-1
        =f.submit "Buscar"
    - if @users.any?
      %table.table-striped.table-hover.user-list
        %th Login
        %th Nombre
        %th Apellidos
        %th
        - @users.each do |u|
          -#.col-md-12
          %tr
            %td
              =u.login
            %td
              =u.name
            %td
              =u.last_name
            %td
              -unless current_user.following.include?(u)
                .col-md-2
                .col-md-2
                  = button_to "Seguir", following_user_path(u), method: :post, class:"btn btn-primary"
              -else
                .col-md-2
                  .following-status Siguiendo ✔
                .col-md-2
                  = button_to "No Seguir", unfollowing_user_path(u), method: :post, class:"btn btn-danger"

app/views/home/_trends.html.haml
#usr-favourites-resume.col-md-12
  %h3
    Trends para tí:

  %ul
  -Post.followers(current_user.id).group_by(&:post_id).sort.to_h.each do |num,posts|
    -posts.each do |post|
      %li=post.user.login
      %p.tab
        =post.text

app/views/home/_wall.html.haml
#wall.tab-pane.fade.in.active
  #tab-content1.content
  -# %h1
  -#   Inicio
  %h3
    TwiX
  %center
    -#%img{src:"https://blog.codepen.io/wp-content/uploads/2012/06/Button-Fill-Black-Large.png", class:"wall-icon"}
  %hr
  -@posts.each do |p|
    -#%fieldset
      -#%legend
    .col-md-12
      .col-md-1
        -if p.user && p.user.asset
          =image_tag p.user.asset.url, class:"img-rounded post-usr-img"

      .col-md-11
        -if p.user
          .post-login
            %b="#{p.user.login}"
        -#.post-name
          ="#{p.user.name} #{p.user.last_name}"
        .post-date
          ="#{p.created_at.strftime("%H:%M %d-%m-%Y")}"
        -if p.post
          %b
            %i="Retwix #{p.post.user.login}"
          .post-comments.col-md-12
            %p
              =p.text
            -p.assets.each do |a|
              .post-assets-container
                =image_tag a.url, class:"col-md-12 col-xs-12 post-assets"
        -else
          .post-comments.col-md-12
            %p
              =p.text
            -p.assets.each do |a|
              .post-assets-container
                =image_tag a.url, class:"col-md-12 col-xs-12 post-assets"

        -#%hr

        -#ACCIONES
        .col-md-6.text-left
          =link_to "Comentar", comment_post_path(p)
          |
          ="Comentarios #{Post.where(ancestry:p.id).count}"
          |
          ="Retwix #{Post.where(post_id:p.id).count}"
          |
          =link_to "Favorito", user_favorite_post_path(p)

        .col-md-6.text-right
          -if p.user.eql?(current_user)
            = link_to 'Editar', edit_post_path(p), remote: true
            |
            = link_to 'Borrar', p, method: :delete, data: { confirm: '¿Está seguro?' }
          -elsif current_user.posts.where(post_id:p.id).blank?
            -#Verificamos si el twex no lo ha twexteado ya
            = link_to 'Retwex', retwex_post_path(p)

        -#COMENTARIOS
        -if Post.where(ancestry:p.id).any?
          .post-comments.col-md-12
            -Post.where(ancestry:p.id).each do |c|
              %p
                %b="#{c.user.login} (#{c.created_at.strftime("%H:%M %d-%m-%Y")}): "
                ="#{c.text}"
    %hr.col-md-12

app/views/home/index.html.haml
.col-md-offset-2.col-md-8
  .col-md-4
    #usr-info-container
      =render partial: "info_user"
    -#follow-info-container
      =render partial: "follow"
    #favourites-container
      =render partial: "favourites"
    #trends-container
      =render partial: "trends"
  .col-md-8
    -#.content-container
    -if notice
      .notice
        %p#notice= notice
    .tab-content.col-md-12
      =render partial: "wall"
      =render partial: "search"
      =render partial: "notifications"
      =render partial: "messages"
  =link_to image_tag("tuxbymail.png",class:"new-post"), new_post_path, remote: true